FROM php:8.0-apache

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get update -y && apt-get install -y libpng-dev libfreetype6-dev libyaml-dev

RUN docker-php-ext-configure gd \
    && docker-php-ext-install gd

RUN usermod -u 1000 www-data

#RUN pecl install xdebug && docker-php-ext-enable xdebug

# Enable Apache mod_rewrite
RUN a2enmod rewrite